package aws.bosnia.demo;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@DynamoDBTable(tableName = "books")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Book {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName="added_on")
    @DynamoDBAutoGeneratedTimestamp
    private String addedOn;

    @DynamoDBAttribute
    private String name;

    public Book(String name) {
        this.name = name;
    }
}

