package aws.bosnia.demo;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@DynamoDBTable(tableName = "Timestamps")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Demo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName="date_time")
    @DynamoDBAutoGeneratedTimestamp
    private String createdOn;
}

